//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace engmercedes.admin.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public int ID { get; set; }
        public string KULLANICIADI { get; set; }
        public string KULLANICISIFRE { get; set; }
        public byte[] KULLANICIRESIM { get; set; }
        public Nullable<System.DateTime> LOGINDATE { get; set; }
        public string KULLANICITELEFON { get; set; }
        public Nullable<System.DateTime> LOGOUTDATE { get; set; }
        public string KULLANICIMAİL { get; set; }
    }
}
