//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace engmercedes.admin.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sirket
    {
        public int ID { get; set; }
        public string HAKKIMIZDA { get; set; }
        public string MISYONUMUZ { get; set; }
        public string VIZYONUMUZ { get; set; }
        public byte[] RESIM1 { get; set; }
        public byte[] RESIM2 { get; set; }
        public byte[] RESIM3 { get; set; }
    }
}
