//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace engmercedes.admin.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_UrunDetay
    {
        public int ID { get; set; }
        public string URUNAD { get; set; }
        public string URUNACIKLAMA { get; set; }
        public Nullable<decimal> URUNFIYAT { get; set; }
        public string KATEGORIADI { get; set; }
        public string ALTKATEGORIADI { get; set; }
        public string MARKAADI { get; set; }
        public Nullable<bool> ISAPPROVED { get; set; }
        public byte[] URUNILKRESIM { get; set; }
        public string URUNILKRESIMYOL { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<System.DateTime> UPDATEDDATE { get; set; }
    }
}
