//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace engmercedes.UI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AltReklam
    {
        public int ID { get; set; }
        public byte[] REKLAMRESIM1 { get; set; }
        public byte[] C_REKLAMRESIM2 { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<System.DateTime> UPDATEDDATE { get; set; }
    }
}
