//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace engmercedes.UI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ayarlar
    {
        public int ID { get; set; }
        public string SITEBASLIK { get; set; }
        public byte[] SITELOGO { get; set; }
        public string SITEACIKLAMA { get; set; }
        public string SITEMAIL { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<System.DateTime> UPDATEDDATE { get; set; }
        public string SITELOGOYOL { get; set; }
        public string SITETELEFON { get; set; }
        public string SITETELEFON2 { get; set; }
        public string SITEADRES { get; set; }
    }
}
