//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace engmercedes.UI.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ENGMERCEDESEntities : DbContext
    {
        public ENGMERCEDESEntities()
            : base("name=ENGMERCEDESEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AltKategori> AltKategori { get; set; }
        public virtual DbSet<Ayarlar> Ayarlar { get; set; }
        public virtual DbSet<Kategori> Kategori { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<Marka> Marka { get; set; }
        public virtual DbSet<Slider> Slider { get; set; }
        public virtual DbSet<SosyalMedya> SosyalMedya { get; set; }
        public virtual DbSet<Urun> Urun { get; set; }
        public virtual DbSet<UrunResim> UrunResim { get; set; }
        public virtual DbSet<vw_AltKatAndKat> vw_AltKatAndKat { get; set; }
        public virtual DbSet<vw_UrunDetay> vw_UrunDetay { get; set; }
        public virtual DbSet<vw_UrunModel> vw_UrunModel { get; set; }
        public virtual DbSet<vw_UIUrunDetay> vw_UIUrunDetay { get; set; }
        public virtual DbSet<AltReklam> AltReklam { get; set; }
        public virtual DbSet<Reklam> Reklam { get; set; }
        public virtual DbSet<Sirket> Sirket { get; set; }
        public virtual DbSet<vw_UrunList> vw_UrunList { get; set; }
        public virtual DbSet<vw_AltAndKat> vw_AltAndKat { get; set; }
        public virtual DbSet<vw_UIUrunDetay1> vw_UIUrunDetay1Set { get; set; }
        public virtual DbSet<vw_UrunDetay1> vw_UrunDetay1Set { get; set; }
        public virtual DbSet<vw_UrunModel1> vw_UrunModel1Set { get; set; }
    
        public virtual int LogInDate(Nullable<int> id, Nullable<System.DateTime> logindate)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var logindateParameter = logindate.HasValue ?
                new ObjectParameter("logindate", logindate) :
                new ObjectParameter("logindate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LogInDate", idParameter, logindateParameter);
        }
    
        public virtual int LogOutDate(Nullable<int> id, Nullable<System.DateTime> dateout)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var dateoutParameter = dateout.HasValue ?
                new ObjectParameter("dateout", dateout) :
                new ObjectParameter("dateout", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LogOutDate", idParameter, dateoutParameter);
        }
    
        [DbFunction("ENGMERCEDESEntities", "funcGetProductDetail")]
        public virtual IQueryable<funcGetProductDetail_Result> funcGetProductDetail(Nullable<int> urunid)
        {
            var urunidParameter = urunid.HasValue ?
                new ObjectParameter("urunid", urunid) :
                new ObjectParameter("urunid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<funcGetProductDetail_Result>("[ENGMERCEDESEntities].[funcGetProductDetail](@urunid)", urunidParameter);
        }
    }
}
